enyo.depends(
	"ui.css",
	"Animator.js",
	// "Media.js",
	// "Audio.js",
	"BaseLayout.js",
	"Image.js",
	"Input.js",
	"RichText.js",
	"TextArea.js",
	"Select.js",
	"Group.js",
	"GroupItem.js",
	"ToolDecorator.js",
	"Button.js",
	"Checkbox.js",
	"Repeater.js",
	"DragAvatar.js",
	"FloatingLayer.js",
	"Popup.js",
	"Selection.js",
	"Sound.js"
);
